


version: '3'
services:
  edge:
    image: globalenigma/docker-edge:latest
    restart: 'no'
    environment:
            # VNCPASSWD: '<unset>'
      VNCRESOLUTION: '1920x1080'
    ports:
      - '127.0.0.1:5901:5901'
    volumes:
      - './data/userdata:/home/user/userdata'
      - './data/downloads:/home/user/downloads'







